# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nX2_Zw2ApmUKYnDVDyzY8_2k-u4hBiAN

REAL CODE
"""

# =========================
# BLOCK 1: EXPLORE DATASET
# =========================

from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path
import glob
import pandas as pd
import numpy as np
import SimpleITK as sitk

# >>> SỬA CHỖ NÀY <<<
DATA_DIR = Path("/content/drive/MyDrive/USTH files/luna")

assert DATA_DIR.exists(), f"DATA_DIR not found: {DATA_DIR}"
ann_path = DATA_DIR / "annotations.csv"
assert ann_path.exists(), "annotations.csv not found"

# 1) Count files
mhd_paths = sorted(glob.glob(str(DATA_DIR/"*.mhd")))
raw_paths = sorted(glob.glob(str(DATA_DIR/"*.raw")))
print("annotations.csv:", ann_path.exists())
print("mhd count:", len(mhd_paths))
print("raw count:", len(raw_paths))
print("\nSample .mhd:", mhd_paths[:3])
print("Sample .raw:", raw_paths[:3])

# 2) Read annotations
df = pd.read_csv(ann_path)
print("\nAnnotations shape:", df.shape)
print("Columns:", df.columns.tolist())
display(df.head(5))

print("\nMissing values:\n", df.isna().sum())

print("\nUnique seriesuid:", df["seriesuid"].astype(str).nunique())
display(df["seriesuid"].astype(str).value_counts().head(10))

# 3) Index mhd by stem = seriesuid
mhd_index = {Path(p).stem: Path(p) for p in mhd_paths}
series_in_csv = set(df["seriesuid"].astype(str).unique())
series_in_mhd = set(mhd_index.keys())

missing_mhd = sorted(list(series_in_csv - series_in_mhd))
extra_mhd   = sorted(list(series_in_mhd - series_in_csv))

print("\nTotal .mhd indexed:", len(mhd_index))
print("Series in CSV but missing .mhd:", len(missing_mhd))
print("mhd files not referenced in CSV:", len(extra_mhd))
print("Examples missing_mhd:", missing_mhd[:3])
print("Examples extra_mhd:", extra_mhd[:3])

# 4) Keep only rows we can actually use (have the scan)
df["seriesuid"] = df["seriesuid"].astype(str)
df_use = df[df["seriesuid"].isin(mhd_index.keys())].copy()
print("\nRows kept (have .mhd):", len(df_use))
print("Unique scans available:", df_use["seriesuid"].nunique())
display(df_use.head(5))

# 5) Load one scan & show metadata (direction, spacing, origin, min/max)
def load_scan(seriesuid: str):
    img = sitk.ReadImage(str(mhd_index[seriesuid]))
    vol = sitk.GetArrayFromImage(img)  # (z,y,x)
    return img, vol

sid_demo = sorted(mhd_index.keys())[0]
img_demo, vol_demo = load_scan(sid_demo)

print("\nDemo seriesuid:", sid_demo)
print("direction:", img_demo.GetDirection())
print("spacing xyz:", img_demo.GetSpacing())
print("origin xyz:", img_demo.GetOrigin())
print("size xyz:", img_demo.GetSize())
print("vol shape (z,y,x):", vol_demo.shape)
print("min/max:", float(vol_demo.min()), float(vol_demo.max()))

# 6) Transform: normalize CT to [0,1] using verified range [-1000,3000]
def normalize_ct(vol_zyx: np.ndarray, vmin=-1000.0, vmax=3000.0):
    vol = np.clip(vol_zyx.astype(np.float32), vmin, vmax)
    vol = (vol - vmin) / (vmax - vmin + 1e-8)
    return vol

# 7) World -> index helper
def world_to_index(img, x, y, z):
    return img.TransformPhysicalPointToIndex((float(x), float(y), float(z)))

# quick sanity: pick 1 row from df_use and check inside bounds
row = df_use.iloc[0]
img0, vol0 = load_scan(row["seriesuid"])
cx, cy, cz = world_to_index(img0, row["coordX"], row["coordY"], row["coordZ"])
sx, sy, sz = img0.GetSize()
inside = (0 <= cx < sx) and (0 <= cy < sy) and (0 <= cz < sz)
print("\nSanity world->index inside volume:", inside, " index(x,y,z)=", (cx,cy,cz))

# =========================
# BLOCK 2: MODEL (train + eval)
# =========================

!pip -q install scipy
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm

from scipy.ndimage import binary_closing, binary_opening, label, generate_binary_structure

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device, "| cuda:", torch.cuda.is_available())

# 1) Rough lung mask (thô, đủ để lọc gan/xương)
def rough_lung_mask(vol_raw_zyx):
    mask = vol_raw_zyx < -400
    st = generate_binary_structure(3, 1)
    mask = binary_opening(mask, structure=st, iterations=1)
    mask = binary_closing(mask, structure=st, iterations=2)
    lbl, n = label(mask)
    if n == 0:
        return mask
    counts = np.bincount(lbl.ravel()); counts[0] = 0
    keep = counts.argsort()[-2:]   # top2 components
    return np.isin(lbl, keep)

# 2) Cache lung masks + GT centers per scan (for hard negatives)
lung_cache = {}
gt_center_cache = {}

for sid in sorted(mhd_index.keys()):
    img, vol_raw = load_scan(sid)
    lung_cache[sid] = rough_lung_mask(vol_raw)
    rows = df_use[df_use["seriesuid"] == sid]
    centers=[]
    for _, r in rows.iterrows():
        centers.append(world_to_index(img, r["coordX"], r["coordY"], r["coordZ"]))
    gt_center_cache[sid] = centers

print("cached scans:", len(lung_cache))

# 3) Patch crop
def crop_patch(vol_zyx, center_xyz, patch_size=64):
    cx, cy, cz = center_xyz
    r = patch_size // 2
    zc, yc, xc = cz, cy, cx  # convert to z,y,x

    z1, z2 = zc - r, zc + r
    y1, y2 = yc - r, yc + r
    x1, x2 = xc - r, xc + r

    pad_z1 = max(0, -z1); pad_y1 = max(0, -y1); pad_x1 = max(0, -x1)
    pad_z2 = max(0, z2 - vol_zyx.shape[0]); pad_y2 = max(0, y2 - vol_zyx.shape[1]); pad_x2 = max(0, x2 - vol_zyx.shape[2])

    z1 = max(0, z1); y1 = max(0, y1); x1 = max(0, x1)
    z2 = min(vol_zyx.shape[0], z2); y2 = min(vol_zyx.shape[1], y2); x2 = min(vol_zyx.shape[2], x2)

    patch = vol_zyx[z1:z2, y1:y2, x1:x2]
    if any([pad_z1, pad_z2, pad_y1, pad_y2, pad_x1, pad_x2]):
        patch = np.pad(patch,
                       ((pad_z1,pad_z2),(pad_y1,pad_y2),(pad_x1,pad_x2)),
                       mode="constant",
                       constant_values=0.0)
    assert patch.shape == (patch_size, patch_size, patch_size)

    offset = (x1 - pad_x1, y1 - pad_y1, z1 - pad_z1)  # virtual patch origin in global coords
    return patch, offset

def far_from_gt(center_xyz, gt_centers, min_dist_vox=16):
    cx,cy,cz = center_xyz
    for (gx,gy,gz) in gt_centers:
        if (cx-gx)**2 + (cy-gy)**2 + (cz-gz)**2 < (min_dist_vox**2):
            return False
    return True

# 4) Train/test split by scan (avoid leakage)
all_sids = sorted(df_use["seriesuid"].unique())
split = int(0.8 * len(all_sids))
train_sids = set(all_sids[:split])
test_sids  = set(all_sids[split:])

train_df = df_use[df_use["seriesuid"].isin(train_sids)].copy()
test_df  = df_use[df_use["seriesuid"].isin(test_sids)].copy()

print("train scans:", len(train_sids), "train rows:", len(train_df))
print("test scans:", len(test_sids), "test rows:", len(test_df))

# 5) Dataset: multi-task (cls + offset regression) with hard negatives in lung
import random

class LunaRegDatasetHardNeg(Dataset):
    def __init__(self, df_use, patch_size=64, neg_ratio=2.0, seed=0, min_dist_vox=16):
        self.df = df_use.reset_index(drop=True)
        self.patch_size = patch_size
        self.neg_ratio = float(neg_ratio)
        self.min_dist_vox = int(min_dist_vox)
        self.rng = random.Random(seed)

        self.pos_items = list(range(len(self.df)))
        self.n_neg = int(len(self.pos_items) * self.neg_ratio)
        self.all_sids = sorted(list(mhd_index.keys()))

    def __len__(self):
        return len(self.pos_items) + self.n_neg

    def __getitem__(self, idx):
        is_pos = idx < len(self.pos_items)
        r = self.patch_size // 2

        if is_pos:
            row = self.df.iloc[idx]
            sid = row["seriesuid"]
            img, vol_raw = load_scan(sid)
            vol = normalize_ct(vol_raw)

            cx, cy, cz = world_to_index(img, row["coordX"], row["coordY"], row["coordZ"])
            patch, offset = crop_patch(vol, (cx,cy,cz), self.patch_size)

            px = cx - offset[0]; py = cy - offset[1]; pz = cz - offset[2]
            cx0, cy0, cz0 = r, r, r

            dx = (px - cx0) / r
            dy = (py - cy0) / r
            dz = (pz - cz0) / r

            cls = 1.0
            mask = 1.0
            off = np.array([dx,dy,dz], dtype=np.float32)

        else:
            sid = self.rng.choice(self.all_sids)
            img, vol_raw = load_scan(sid)
            vol = normalize_ct(vol_raw)

            lung = lung_cache[sid]
            gt = gt_center_cache.get(sid, [])

            D,H,W = lung.shape
            ok = False
            for _ in range(300):
                z = self.rng.randint(r, D-r-1)
                y = self.rng.randint(r, H-r-1)
                x = self.rng.randint(r, W-r-1)
                if lung[z,y,x] and far_from_gt((x,y,z), gt, min_dist_vox=self.min_dist_vox):
                    ok = True
                    cx,cy,cz = x,y,z
                    break
            if not ok:
                cx = self.rng.randint(r, W-r-1)
                cy = self.rng.randint(r, H-r-1)
                cz = self.rng.randint(r, D-r-1)

            patch, _ = crop_patch(vol, (cx,cy,cz), self.patch_size)
            cls = 0.0
            mask = 0.0
            off = np.zeros(3, dtype=np.float32)

        x = torch.from_numpy(patch[None,...].astype(np.float32))  # (1,D,H,W)
        cls = torch.tensor([cls], dtype=torch.float32)           # (1,)
        off = torch.from_numpy(off)                              # (3,)
        mask = torch.tensor([mask], dtype=torch.float32)         # (1,)
        return x, cls, off, mask

# 6) Model
class Tiny3DDet(nn.Module):
    def __init__(self, base=16):
        super().__init__()
        self.feat = nn.Sequential(
            nn.Conv3d(1, base, 3, padding=1), nn.InstanceNorm3d(base), nn.ReLU(inplace=True),
            nn.MaxPool3d(2),

            nn.Conv3d(base, base*2, 3, padding=1), nn.InstanceNorm3d(base*2), nn.ReLU(inplace=True),
            nn.MaxPool3d(2),

            nn.Conv3d(base*2, base*4, 3, padding=1), nn.InstanceNorm3d(base*4), nn.ReLU(inplace=True),
            nn.AdaptiveAvgPool3d(1),
        )
        self.head_cls = nn.Linear(base*4, 1)
        self.head_reg = nn.Linear(base*4, 3)

    def forward(self, x):
        f = self.feat(x).flatten(1)
        p = torch.sigmoid(self.head_cls(f))   # (B,1)
        off = torch.tanh(self.head_reg(f))    # (B,3)
        return p, off

def train_epoch_det(model, loader, optim, lam_reg=1.0):
    model.train()
    tot = 0.0
    for x, cls, off, mask in tqdm(loader, leave=False):
        x = x.to(device)
        cls = cls.to(device)
        off = off.to(device)
        mask = mask.to(device)

        p, pred_off = model(x)
        loss_cls = F.binary_cross_entropy(p, cls)
        reg = F.smooth_l1_loss(pred_off, off, reduction="none").mean(dim=1, keepdim=True)
        loss_reg = (reg * mask).sum() / (mask.sum() + 1e-8)
        loss = loss_cls + lam_reg * loss_reg

        optim.zero_grad()
        loss.backward()
        optim.step()
        tot += loss.item() * x.size(0)
    return tot / len(loader.dataset)

@torch.no_grad()
def eval_epoch_det(model, loader, lam_reg=1.0):
    model.eval()
    tot = 0.0
    for x, cls, off, mask in loader:
        x = x.to(device); cls = cls.to(device); off = off.to(device); mask = mask.to(device)
        p, pred_off = model(x)
        loss_cls = F.binary_cross_entropy(p, cls)
        reg = F.smooth_l1_loss(pred_off, off, reduction="none").mean(dim=1, keepdim=True)
        loss_reg = (reg * mask).sum() / (mask.sum() + 1e-8)
        loss = loss_cls + lam_reg * loss_reg
        tot += loss.item() * x.size(0)
    return tot / len(loader.dataset)

# 7) Train
patch_size = 64
train_ds = LunaRegDatasetHardNeg(train_df, patch_size=patch_size, neg_ratio=2.0, seed=0, min_dist_vox=16)
test_ds  = LunaRegDatasetHardNeg(test_df,  patch_size=patch_size, neg_ratio=2.0, seed=1, min_dist_vox=16)

train_loader = DataLoader(train_ds, batch_size=8, shuffle=True, num_workers=0)
test_loader  = DataLoader(test_ds,  batch_size=8, shuffle=False, num_workers=0)

model = Tiny3DDet(base=16).to(device)
optim = torch.optim.Adam(model.parameters(), lr=1e-3)

epochs = 15
for ep in range(1, epochs+1):
    tr = train_epoch_det(model, train_loader, optim, lam_reg=1.0)
    va = eval_epoch_det(model, test_loader, lam_reg=1.0)
    print(f"epoch {ep}: train={tr:.4f} val={va:.4f}")

# 8) Evaluate: patch-level mean distance on some positives
import matplotlib.pyplot as plt

def dist_voxel(a_xyz, b_xyz):
    ax,ay,az = a_xyz
    bx,by,bz = b_xyz
    return float(np.sqrt((ax-bx)**2 + (ay-by)**2 + (az-bz)**2))

@torch.no_grad()
def visualize_patch_det(model, ds, idx=0):
    model.eval()
    x, cls, off_gt, mask = ds[idx]
    if float(cls.item()) != 1.0:
        return None

    xin = x.unsqueeze(0).to(device)
    p, off_pred = model(xin)
    p = float(p.item())
    off_pred = off_pred[0].detach().cpu().numpy()

    patch = x[0].numpy()  # (z,y,x)
    D,H,W = patch.shape
    r = D//2

    gt_center = np.array([r,r,r], dtype=np.float32)
    pred_center = gt_center + off_pred * r
    pred_center = np.clip(pred_center, [0,0,0], [W-1,H-1,D-1])

    px,py,pz = pred_center.astype(int)
    gx,gy,gz = gt_center.astype(int)

    fig, axs = plt.subplots(1,3, figsize=(15,5))
    axs[0].imshow(patch[gz], cmap="gray")
    axs[0].scatter([gx],[gy], marker="x", s=80)
    axs[0].scatter([px],[py], marker="o", s=60, facecolors="none")
    axs[0].set_title("Axial (z=GT)  x=GT  o=Pred"); axs[0].axis("off")

    axs[1].imshow(patch[:, gy, :], cmap="gray")
    axs[1].scatter([gx],[gz], marker="x", s=80)
    axs[1].scatter([px],[pz], marker="o", s=60, facecolors="none")
    axs[1].set_title("Coronal (y=GT)"); axs[1].axis("off")

    axs[2].imshow(patch[:, :, gx], cmap="gray")
    axs[2].scatter([gy],[gz], marker="x", s=80)
    axs[2].scatter([py],[pz], marker="o", s=60, facecolors="none")
    axs[2].set_title("Sagittal (x=GT)"); axs[2].axis("off")

    plt.suptitle(f"pred p={p:.3f} | pred_center={tuple(map(int,(px,py,pz)))}")
    plt.show()

    return p, (gx,gy,gz), (px,py,pz)

# compute mean distance on 20 positive samples
dists=[]
shown=0
for i in range(min(len(train_ds), 200)):
    out = visualize_patch_det(model, train_ds, idx=i)
    if out is None:
        continue
    p, gt, pred = out
    dists.append(dist_voxel(gt, pred))
    shown += 1
    if shown == 5:
        break

# just distance stats without plotting too many:
dists2=[]
cnt=0
for i in range(len(train_ds)):
    x, cls, off, mask = train_ds[i]
    if float(cls.item())==1.0:
        xin = x.unsqueeze(0).to(device)
        with torch.no_grad():
            p, off_pred = model(xin)
        off_pred = off_pred[0].detach().cpu().numpy()
        r = patch_size//2
        gt_center = np.array([r,r,r], dtype=np.float32)
        pred_center = gt_center + off_pred*r
        pred_center = np.clip(pred_center, [0,0,0], [patch_size-1]*3)
        dists2.append(dist_voxel(gt_center, pred_center))
        cnt += 1
        if cnt == 30:
            break
print("mean dist voxel (first 30 pos):", float(np.mean(dists2)))

# =========================
# BLOCK 3: DEMO REAL (whole scan)
# =========================

import numpy as np
import matplotlib.pyplot as plt

@torch.no_grad()
def whole_scan_grid_detect_lung(model, vol_norm_zyx, lung_mask_zyx,
                               patch_size=64, step=32, topk=10, batch_size=16):
    model.eval()
    D,H,W = vol_norm_zyx.shape
    r = patch_size//2

    xs = list(range(r, W-r, step))
    ys = list(range(r, H-r, step))
    zs = list(range(r, D-r, step))

    centers=[]
    for z in zs:
        for y in ys:
            for x in xs:
                if lung_mask_zyx[z,y,x]:
                    centers.append((x,y,z))

    print("grid centers in lung:", len(centers))

    results=[]
    for i in range(0, len(centers), batch_size):
        batch_centers = centers[i:i+batch_size]
        patches=[]
        for (x,y,z) in batch_centers:
            patch,_ = crop_patch(vol_norm_zyx, (x,y,z), patch_size)
            patches.append(patch)
        xb = torch.from_numpy(np.stack(patches)[:,None].astype(np.float32)).to(device)
        p, off = model(xb)

        p = p.squeeze(1).detach().cpu().numpy()
        off = off.detach().cpu().numpy()

        for j,(gcx,gcy,gcz) in enumerate(batch_centers):
            dx,dy,dz = off[j]
            px = float(np.clip(gcx + dx*r, 0, W-1))
            py = float(np.clip(gcy + dy*r, 0, H-1))
            pz = float(np.clip(gcz + dz*r, 0, D-1))
            results.append({
                "p": float(p[j]),
                "pred_center_xyz": (px,py,pz),
                "grid_center_xyz": (gcx,gcy,gcz),
                "pred_off": (float(dx),float(dy),float(dz))
            })

    results.sort(key=lambda d: d["p"], reverse=True)
    return results[:topk]

def dist_mm(a_xyz, b_xyz, spacing_xyz):
    ax,ay,az = a_xyz
    bx,by,bz = b_xyz
    sx,sy,sz = spacing_xyz
    return float(np.sqrt(((ax-bx)*sx)**2 + ((ay-by)*sy)**2 + ((az-bz)*sz)**2))

# 1) Pick a test scan (has GT)
sid = sorted(test_df["seriesuid"].unique())[0]
print("Demo scan:", sid)

img, vol_raw = load_scan(sid)
vol = normalize_ct(vol_raw)
lung = lung_cache[sid]
spacing = img.GetSpacing()

# GT centers
gt_rows = test_df[test_df["seriesuid"] == sid]
gt_centers=[]
for _, r in gt_rows.iterrows():
    gt_centers.append(world_to_index(img, r["coordX"], r["coordY"], r["coordZ"]))
print("GT nodules:", len(gt_centers))
print("First GT:", gt_centers[:3])

# 2) Run whole scan detection
topk_preds = whole_scan_grid_detect_lung(model, vol, lung, patch_size=64, step=32, topk=10, batch_size=16)

for i,d in enumerate(topk_preds,1):
    pred = d["pred_center_xyz"]
    best = min(dist_mm(pred, gt, spacing) for gt in gt_centers) if len(gt_centers)>0 else None
    print(i, "p=", round(d["p"],4),
          "pred_center_xyz=", tuple(round(v,1) for v in pred),
          "best_dist_mm=", (None if best is None else round(best,2)))

# 3) Overlay visualization for top-1
best_pred = topk_preds[0]["pred_center_xyz"]
px,py,pz = map(int, best_pred)

plt.figure(figsize=(6,6))
plt.imshow(vol[pz], cmap="gray")
plt.scatter([px],[py], marker="o", s=70, facecolors="none")  # pred

# show GT near this z
for (gx,gy,gz) in gt_centers:
    if abs(gz - pz) <= 1:
        plt.scatter([gx],[gy], marker="x", s=70)
plt.title(f"Pred o at z={pz} | GT x (if |dz|<=1)")
plt.axis("off")
plt.show()